# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=50)),
                ('businessDesc', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('location', models.CharField(max_length=50)),
                ('businessType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhoodName', models.CharField(choices=[('biryogo', 'biryogo'), ('nyamabuye', 'nyamabuye'), ('nyagatovu', 'nyagatovu'), ('gatenga', 'gatenga'), ('kinyoni', 'kinyoni'), ('kabusunzu', 'kabusunzu'), ('mu kidoge', 'mu kidoge'), ('kabuye', 'kabuye'), ('batsinda', 'batsinda'), ('rutunga', 'rutunga'), ('jabana', 'jabana')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(default=None)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='busines_pics/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=50)),
                ('ProdType', models.CharField(max_length=50)),
                ('prodPrice', models.IntegerField(default=None)),
                ('prodQuantity', models.IntegerField(default=None)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile_pics/')),
                ('hoodName', models.TextField(max_length=200)),
                ('bio', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('neighbourhood', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(default=None)),
                ('general_loc', models.CharField(max_length=50)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nisapp.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Neighborhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Owner'),
        ),
    ]
