# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=50)),
                ('businessDesc', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Gatsata', 'Gatsata'), ('Nyamirambo', 'Nyamirambo'), ('Remera', 'Remera'), ('Nyabugogo', 'Nyabugogo'), ('kimironko', 'kimironko'), ('nyarutarama', 'nyarutarama'), ('muhima', 'muhima'), ('kigali', 'kigali'), ('kicukiro', 'kicukiro')], max_length=40)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(choices=[('biryogo', 'biryogo'), ('nyamabuye', 'nyamabuye'), ('nyagatovu', 'nyagatovu'), ('gatenga', 'gatenga'), ('kinyoni', 'kinyoni'), ('kabusunzu', 'kabusunzu'), ('karama', 'karama'), ('kabuye', 'kabuye'), ('batsinda', 'batsinda'), ('kagarama', 'kagarama'), ('karuruma', 'karururma')], max_length=40)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', tinymce.models.HTMLField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Neighborhood')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('ProdType', models.CharField(max_length=50)),
                ('prodPrice', models.IntegerField(default=None)),
                ('prodQuantity', models.IntegerField(default=None)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile_pics/')),
                ('bio', models.TextField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('contact', models.IntegerField(default=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Location'),
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.Neighborhood'),
        ),
    ]
