# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='loc_name',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('Gatsata', 'Gatsata'), ('Nyamirambo', 'Nyamirambo'), ('Remera', 'Remera'), ('Nyabugogo', 'Nyabugogo'), ('kimironko', 'kimironko'), ('nyarutarama', 'nyarutarama'), ('muhima', 'muhima'), ('kigali', 'kigali'), ('kicukiro', 'kicukiro')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
