# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('Gatsata', 'Gatsata'), ('Nyamirambo', 'Nyamirambo'), ('Remera', 'Remera'), ('Nyabugogo', 'Nyabugogo'), ('Kimironko', 'Kimironko'), ('Nyarutarama', 'Nyarutarama'), ('Muhima', 'Muhima'), ('Kigali', 'Kigali'), ('Kicukiro', 'Kicukiro'), ('Gikondo', 'Gikondo'), ('Gacuriro', 'Gacuriro'), ('Kacyiru', 'Kacyiru'), ('Kibagabaga', 'Kibagabaga'), ('Gisozi', 'Gisozi'), ('Kabeza', 'Kabeza')], max_length=40),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(choices=[('Biryogo', 'Biryogo'), ('Nyamabuye', 'Nyamabuye'), ('Nyagatovu', 'Nyagatovu'), ('Gatenga', 'Gatenga'), ('Kinyoni', 'Kinyoni'), ('Kabusunzu', 'Kabusunzu'), ('Karama', 'Karama'), ('Kabuye', 'Kabuye'), ('Batsinda', 'Batsinda'), ('Kagarama', 'Kagarama'), ('Karuruma', 'Karururma'), ('Kinamba', 'Kinamba'), ('Kacyiru1', 'Kacyiru1'), ('Kigarama', 'Kigarama'), ('Kabeza2', 'Kabeza2'), ('Kibagabaga1', 'Kibagabaga1'), ('Kagugu', 'Kagugu'), ('Nyakabanda', 'Nyakabanda'), ('Niboye', 'Niboye'), ('Kinyinya', 'Kinyinya')], max_length=40),
        ),
    ]
