# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0002_auto_20191118_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(choices=[('biryogo', 'biryogo'), ('nyamabuye', 'nyamabuye'), ('nyagatovu', 'nyagatovu'), ('gatenga', 'gatenga'), ('kinyoni', 'kinyoni'), ('kabusunzu', 'kabusunzu'), ('karama', 'karama'), ('kabuye', 'kabuye'), ('batsinda', 'batsinda'), ('kagarama', 'kagarama'), ('karuruma', 'karururma')], max_length=40),
        ),
    ]
