# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0003_auto_20191122_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
