# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nisapp', '0004_auto_20191122_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='admin',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
