# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0007_auto_20191202_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prodImage',
        ),
    ]
