# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0008_auto_20191203_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='image',
            new_name='businessImage',
        ),
    ]
